version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ignite_prisma
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=postgres_prisma
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local